### PR TITLE
Add Freezer 3 to Downgrader & Lore Fix

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
## Changes
- Bump Slimefun Version to be able to make the next Change
- Added a Recipe to the Downgrader Machine, Freezer 3 -> Freezer 2, same time as any other recipes.
- Fixed the Lore of the Recycler III, it said a speed of 2, while its a Speed of 4.

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
I have tested the recipe and it works as intended. I have not tested that bumping the version has affected any of the other already implemented mechanics however.

**Comment by FN-FAL113** [comment]
Can you bump the pom.xml version property to 3.3.6 and update the PlayerJoinListener.java changelog for the needed slimefun dev version prior the freezer 3 update or above

**Review by FN-FAL113 — CHANGES_REQUESTED** [review]
Can you bump the pom.xml version property to 3.3.6 and update the PlayerJoinListener.java changelog for the needed slimefun dev version prior the freezer 3 update or above

**Review by FN-FAL113 — APPROVED** [review]
Appreciate it! Happy new year to you mate!

**Comment by JustAHuman-xD** [comment]
You too!

**Pull request merged**
